# Embeds a data file into the library as a byte array.
#
# The upstream C# build ships manifest.json as an embedded assembly resource so the library is
# self-describing with no data files on disk. This reproduces that: `manifest.json` becomes a
# `constexpr` byte span the engine can parse without touching the filesystem.
#
# Generation happens at configure time and the input is added to CMAKE_CONFIGURE_DEPENDS, so
# editing an asset re-runs CMake rather than silently serving a stale copy.
#
#   ts_embed_asset(<out-source-var> <input-file> <symbol>)

function(ts_embed_asset out_source input symbol)
    get_filename_component(input_abs "${input}" ABSOLUTE)

    if(NOT EXISTS "${input_abs}")
        message(FATAL_ERROR "ts_embed_asset: no such file: ${input_abs}")
    endif()

    set(generated "${CMAKE_CURRENT_BINARY_DIR}/generated/${symbol}.cpp")

    file(READ "${input_abs}" hex HEX)
    string(LENGTH "${hex}" hex_length)
    math(EXPR byte_count "${hex_length} / 2")

    # Two hex digits -> "0xNN,". Chunked onto lines so the generated file stays readable and does
    # not trip compiler line-length limits.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " bytes "${bytes}")

    get_filename_component(input_name "${input_abs}" NAME)

    file(CONFIGURE
        OUTPUT "${generated}"
        CONTENT "// Generated by cmake/EmbedAsset.cmake from ${input_name}. Do not edit.
#include \"rom/embedded_assets.hpp\"

namespace ts::assets {

namespace {
constexpr unsigned char k_${symbol}_bytes[] = {
    ${bytes}
};
} // namespace

std::string_view ${symbol}() noexcept
{
    return std::string_view(reinterpret_cast<const char*>(k_${symbol}_bytes), ${byte_count});
}

} // namespace ts::assets
"
        @ONLY)

    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${input_abs}")
    set(${out_source} "${generated}" PARENT_SCOPE)
endfunction()
